### ISSUE TITLE
Fin de playlist 

### ISSUE THREAD

**Issue by Miala-python** [MialaProg/MiYT#24]
Recommence la playlist à la place de page d'accueil

**Comment by Miala-python** [comment]
VidChg: 12
loop.js:76 
loop.js:77 Error known: Cannot read properties of null (reading 'classList')
=> Normal for the first video (see set_bg_vid)
loop.js:192 Uncaught 
pageUpdate @ loop.js:192
setInterval
onYouTubeIframeAPIReady @ loop.js:371
(anonyme) @ www-widgetapi.js:220
(anonyme) @ www-widgetapi.js:220Comprendre cette erreurAI
www-embed-player.js:1842 Uncaught TypeError: Cannot read properties of null (reading 'endSeconds')
    at jy (www-embed-player.js:1842:157)
    at H (www-embed-player.js:1846:357)
jy @ www-embed-player.js:1842
H @ www-embed-player.js:1846Comprendre cette erreurAI
loop.js:194 MiYT state: 0/572.001 => 1
loop.js:194 MiYT state: 0/572.001 => 3
loop.js:234 Try play
loop.js:85 
        
        
       GET https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=undefined&format=json 400 (Bad Request)
changeVideo @ loop.js:85
pageUpdate @ loop.js:179
setInterval
onYouTubeIframeAPIReady @ loop.js:371
(anonyme) @ www-widgetapi.js:220
(anonyme) @ www-widgetapi.js:220Comprendre cette erreurAI
loop.js:94 Set Outro SkipperERR #12 : SyntaxError: Unexpected token 'B', "Bad Request" is not valid JSON
loop.js:194 MiYT state: 0/572.001 => 1
loop.js:194 MiYT state: 0/572.001 => 1
loop.js:194 MiYT state: 1/572.001 => 1
loop.js:194 MiYT state: 2/572.001 => 2
7loop.js:194 MiYT state: 2/572.001 => 2

**Comment by Miala-python** [comment]
Patched bb44a7b
